config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength:

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'top_pages#index'
  resources :users          , only: %i[new create show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :my_pages       , only: %i[index]
  resources :rewards        , only: %i[index]
  resources :quick_routine_templates, only: %i[update]

  get    'login',            to: 'user_sessions#new'
  post   'login',            to: 'user_sessions#create'
  delete 'logout',           to: 'user_sessions#destroy'
  post   'guest_login',      to: 'guest_logins#create'
  post   'linebot/callback', to: 'linebots#callback'

  resources :routines, only: %i[index new show create update destroy] do
    resources :tasks   , only: %i[create update destroy], shallow: true
    resources :copies  , only: %i[create]               , module: :routines
    resources :plays   , only: %i[create update show]   , module: :routines, param: :routine_id, shallow: true
    resources :finishes, only: %i[index]                , module: :routines
  end

  # URLが"routines/**"の形式では、RoutinesコントローラのshowアクションのURLとして認識されてしまうため、pathオプションを"routine"に指定
  namespace :routines, path: 'routine' do
    resources :actives      , only: %i[update]        , param: :routine_id
    resources :posts        , only: %i[index update]  , param: :routine_id
    resources :likes        , only: %i[create destroy], param: :routine_id
    resources :quick_creates, only: %i[create]
  end

  namespace :tasks do
    resources :move_highers, only: %i[update], param: :task_id
    resources :move_lowers , only: %i[update], param: :task_id
    resources :sorts       , only: %i[update], param: :task_id
  end

  namespace :users, path: 'user' do
    resources :notifications  , only: %i[update], param: :user_id
    resources :feature_rewards, only: %i[update], param: :user_id
  end

  resources :contacts, only: %i[show new create]

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback'  => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'terms' , to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    user == Rails.application.credentials.dig(:sidekiq, :user) &&
      password == Rails.application.credentials.dig(:sidekiq, :password)
  end
  mount Sidekiq::Web, at: '/sidekiq'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :admin do
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    resources :rewards, only: %i[index edit update]
    root 'dashboard#index'
  end
end
# rubocop:enable Metrics/BlockLength:

app/models/reward.rb
class Reward < ApplicationRecord
  mount_uploader :image, RewardImageUploader

  has_many :user_rewards   , dependent: :destroy
  has_many :users          , through:   :user_rewards
  has_many :featuring_users, dependent: :nullify     , class_name: 'User', foreign_key: 'feature_reward_id', inverse_of: 'feature_reward'

  validates :name     , presence: true
  validates :condition, presence: true

  scope :for_user,     ->(user_id) { joins(:user_rewards).where(user_rewards: { user_id: }) }
  scope :not_for_user, ->(user)    { where.not(id: user.reward_ids) }
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  def index
    @rewards = Reward.all
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      flash[:notice] = '更新しました'
      redirect_to admin_rewards_path
    else
      render :edit
    end
  end

  private

  def reward_params
    params.require(:reward).permit(:name, :image, :image_cache, :description)
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards        = Reward.includes(:users)
    @feature_reward = current_user.feature_reward
  end
end

app/views/admin/rewards/_form.html.erb
<%= form_with model: reward, url: admin_reward_path(reward), class:"text-center" do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="my-8">
    <%= f.label :image, "称号の画像", class: "block font-semibold mb-2 sm:text-lg" %>
    <%= f.file_field :image, class: "block input input-bordered mx-auto w-8/12 md:text-lg lg:w-1/2", placeholder: "ユーザー名"%>
    <%= f.hidden_field :image_cache %>
    <% if reward.image.url %>
      <%= image_tag reward.image.url, size: '100x100' %>
    <% end %> 
  </div>

  <div class="my-8">
    <%= f.label :name, "称号タイトル", class: "block font-semibold mb-2 sm:text-lg" %>
    <%= f.text_field :name, class: "block input input-bordered mx-auto w-8/12 md:text-lg lg:w-1/2", placeholder: "ユーザー名"%>
  </div>

  <div class=" my-8 ">
    <%= f.label :description, "条件の説明", class: "block font-semibold mb-2 sm:text-lg" %>
    <%= f.text_field :description, class:"block input input-bordered mx-auto w-8/12 md:text-lg lg:w-1/2" %>
  </div>

  <%= f.submit nil, class:"btn bg-gradient-to-tl from-cyan-300 to-cyan-100 mb-5 btn-md min-w-28 sm:text-lg sm:btn-lg sm:min-w-40 lg:min-w-60" %>
<% end %>

app/views/admin/rewards/_reward.html.erb
<div class="m-1 sm:m-3">
  <div class="card bg-base-100 shadow-xl">
    <figure class="px-1 pt-1">
      <% if reward.image.url %>
        <%= image_tag reward.image.url, size: '200x200' %>
      <% end %> 
    </figure>
    <div class="card-body items-center text-center p-2">
      <h2 class="card-title bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-green-500"><%= reward.name %></h2>
      <%= link_to "編集", edit_admin_reward_path(reward), class: "btn btn-success btn-outline" %>
    </div>
  </div>
</div>

app/views/admin/rewards/edit.html.erb
<h1 class="text-center my-10 text-xl font-semibold sm:text-3xl lg:text-4xl">称号編集</h1>

<div class="text-center">
  <%= render "form", reward: @reward %>
  <%= link_to "キャンセル", admin_rewards_path, class: "btn bg-gradient-to-tl from-gray-400 to-gray-100 mx-auto mb-5 min-w-20 sm:text-lg sm:btn-lg sm:max-w-36" %> <br>
</div>

app/views/admin/rewards/index.html.erb
<h1 class="text-xl font-semibold my-5 text-center sm:text-3xl lg:text-4xl">称号一覧</h1>

<div class="p-4 grid sm:grid-cols-2 lg:grid-cols-3">
  <%= render @rewards %>
</div>