config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength:

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'top_pages#index'
  resources :users          , only: %i[new create show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :my_pages       , only: %i[index]
  resources :rewards        , only: %i[index]
  resources :quick_routine_templates, only: %i[update]

  get    'login',            to: 'user_sessions#new'
  post   'login',            to: 'user_sessions#create'
  delete 'logout',           to: 'user_sessions#destroy'
  post   'guest_login',      to: 'guest_logins#create'
  post   'linebot/callback', to: 'linebots#callback'

  resources :routines, only: %i[index new show create update destroy] do
    resources :tasks   , only: %i[create update destroy], shallow: true
    resources :copies  , only: %i[create]               , module: :routines
    resources :plays   , only: %i[create update show]   , module: :routines, param: :routine_id, shallow: true
    resources :finishes, only: %i[index]                , module: :routines
  end

  # URLが"routines/**"の形式では、RoutinesコントローラのshowアクションのURLとして認識されてしまうため、pathオプションを"routine"に指定
  namespace :routines, path: 'routine' do
    resources :actives      , only: %i[update]        , param: :routine_id
    resources :posts        , only: %i[index update]  , param: :routine_id
    resources :likes        , only: %i[create destroy], param: :routine_id
    resources :quick_creates, only: %i[create]
  end

  namespace :tasks do
    resources :move_highers, only: %i[update], param: :task_id
    resources :move_lowers , only: %i[update], param: :task_id
    resources :sorts       , only: %i[update], param: :task_id
  end

  namespace :users, path: 'user' do
    resources :notifications  , only: %i[update], param: :user_id
    resources :feature_rewards, only: %i[update], param: :user_id
  end

  resources :contacts, only: %i[show new create]

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback'  => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'terms' , to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    user == Rails.application.credentials.dig(:sidekiq, :user) &&
      password == Rails.application.credentials.dig(:sidekiq, :password)
  end
  mount Sidekiq::Web, at: '/sidekiq'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :admin do
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    resources :rewards, only: %i[index edit update]
    root 'dashboard#index'
  end
end
# rubocop:enable Metrics/BlockLength:

app/models/reward.rb
class Reward < ApplicationRecord
  mount_uploader :image, RewardImageUploader

  has_many :user_rewards   , dependent: :destroy
  has_many :users          , through:   :user_rewards
  has_many :featuring_users, dependent: :nullify     , class_name: 'User', foreign_key: 'feature_reward_id', inverse_of: 'feature_reward'

  validates :name     , presence: true
  validates :condition, presence: true

  scope :for_user,     ->(user_id) { joins(:user_rewards).where(user_rewards: { user_id: }) }
  scope :not_for_user, ->(user)    { where.not(id: user.reward_ids) }
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  def index
    @rewards = Reward.all
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      flash[:notice] = '更新しました'
      redirect_to admin_rewards_path
    else
      render :edit
    end
  end

  private

  def reward_params
    params.require(:reward).permit(:name, :image, :image_cache, :description)
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards        = Reward.includes(:users)
    @feature_reward = current_user.feature_reward
  end
end

app/views/rewards/_description.html.erb
<div class="card bg-base-100 image-full shadow-xl h-full" id="reward-description-<%= reward.id %>">
  <figure>
    <% if reward.image.url %>
      <%= image_tag reward.image.url, size: '200x200' %>
    <% end %> 
  </figure>
  
  <div class="card-body bg-green-600/85 z-10 p-1 sm:p-2 lg:p-4">
    <h2 class="text-title-custom text-center">未開放</h2>
    <h2 class="text-lg-custom"><%= reward.description %></h2>
  </div>
</div>

app/views/rewards/_reward.html.erb
<div id="reward-zone-<%= reward.id %>">
  <% if reward.users.include?(current_user) %>
    <%= render 'rewards/reward_card', reward: reward, feature_reward: feature_reward %>
  <% else %>
    <%= render 'rewards/description', reward: reward %>
  <% end %>
</div>

app/views/rewards/_reward_card.html.erb
<div class="card bg-base-100 shadow-md" id="reward-card-<%= reward.id %>">
  <!-- 称号画像 -->
  <figure class="px-1 pt-1">
    <% if reward.image.url %>
      <button onclick="document.getElementById('reward-image-<%=reward.id%>').showModal()">
        <%= image_tag reward.image.url, size: '200x200' %>
      </button>
    <% end %> 
  </figure>

  <!-- 称号タイトル -->
  <div class="card-body items-center text-center p-2">
    <%= render 'rewards/reward_title', reward: reward %>
  </div>
</div>

<!-- 画像クリックで表示されるモーダル -->
<dialog id="reward-image-<%=reward.id%>" class="modal w-10/12 mx-auto">
  <div class="modal-box flex justify-center">
    <%= image_tag reward.image.url, class: "w-10/12" %>
  </div>

  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/rewards/_reward_title.html.erb
<!-- プロフィールに設定されている -->
<% if current_user.feature_reward_id == reward.id %>
  <h2 class="text-reward-custom text-lg-custom flex items-center">
    <i class="i-uiw-star-on text-red-500"></i>
    <%= reward.name %>
  </h2>

<!-- 設定されていない -->
<% else %>
  <div class="tooltip tooltip-primary" data-tip="clickでプロフィールに設定">
    <%= button_to users_feature_reward_path(current_user),
        { method: :patch, params: { user: { feature_reward_id: reward.id } } } do
    %>
      <h2 class="text-reward-custom text-lg-custom flex items-center">
        <i class="i-uiw-star-off text-gray-500"></i>
        <%= reward.name %>
      </h2>
    <% end %>
  </div>
<% end %>

app/views/rewards/index.html.erb
<!-- パンくず -->
<div class="breadcrumbs-container-custom">
  <ul>
    <li class="link-text-custom">
      <%= link_to 'マイページ', my_pages_path %>
    </li>
    <li>
      <span class="current-page-text-custom">称号一覧</span>
    </li>
  </ul>
</div>

<h1 class="page-title-custom">称号一覧</h1>

<div class="px-4 grid grid-cols-2 lg:grid-cols-3 gap-3" id="reward-index">
  <%= render @rewards, feature_reward: @feature_reward %>
</div>