config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength:

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ('/')
  root 'top_pages#index'
  resources :users          , only: %i[new create show edit update]
  resources :password_resets, only: %i[new create edit update]
  resources :my_pages       , only: %i[index]
  resources :rewards        , only: %i[index]
  resources :quick_routine_templates, only: %i[update]

  get    'login',            to: 'user_sessions#new'
  post   'login',            to: 'user_sessions#create'
  delete 'logout',           to: 'user_sessions#destroy'
  post   'guest_login',      to: 'guest_logins#create'
  post   'linebot/callback', to: 'linebots#callback'

  resources :routines, only: %i[index new show create update destroy] do
    resources :tasks   , only: %i[create update destroy], shallow: true
    resources :copies  , only: %i[create]               , module: :routines
    resources :plays   , only: %i[create update show]   , module: :routines, param: :routine_id, shallow: true
    resources :finishes, only: %i[index]                , module: :routines
  end

  # URLが"routines/**"の形式では、RoutinesコントローラのshowアクションのURLとして認識されてしまうため、pathオプションを"routine"に指定
  namespace :routines, path: 'routine' do
    resources :actives      , only: %i[update]        , param: :routine_id
    resources :posts        , only: %i[index update]  , param: :routine_id
    resources :likes        , only: %i[create destroy], param: :routine_id
    resources :quick_creates, only: %i[create]
  end

  namespace :tasks do
    resources :move_highers, only: %i[update], param: :task_id
    resources :move_lowers , only: %i[update], param: :task_id
    resources :sorts       , only: %i[update], param: :task_id
  end

  namespace :users, path: 'user' do
    resources :notifications  , only: %i[update], param: :user_id
    resources :feature_rewards, only: %i[update], param: :user_id
  end

  resources :contacts, only: %i[show new create]

  post 'oauth/callback' => 'oauths#callback'
  get 'oauth/callback'  => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider

  get 'terms' , to: 'static_pages#terms'
  get 'policy', to: 'static_pages#policy'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    user == Rails.application.credentials.dig(:sidekiq, :user) &&
      password == Rails.application.credentials.dig(:sidekiq, :password)
  end
  mount Sidekiq::Web, at: '/sidekiq'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :admin do
    get 'login' => 'user_sessions#new', :as => :login
    post 'login' => 'user_sessions#create'
    resources :rewards, only: %i[index edit update]
    root 'dashboard#index'
  end
end
# rubocop:enable Metrics/BlockLength:

app/views/shared/_before_login_header.html.erb
<header id="before-login-header" class="mb-12 sm:mb-14 md:mb-16">
  <div class="fixed top-0 z-50 w-full h-12 sm:h-14 md:h-16 py-3 px-1 sm:px-3 md:px-5 flex justify-between items-center bg-gradient-to-t from-sky-50 to-sky-200">

    <%= link_to root_path, class:"btn btn-sm sm:h-10 md:h-12 w-28 sm:w-36 md:w-44 btn-outline bg-white bg-opacity-30 text-green-600 hover:bg-green-500", id: "header-logo" do %>
      <p class="flex items-center">
        <%= image_tag "logo.jpg", class: "rounded h-6 sm:h-8 md:h-10 mr-1 sm:mr-2 md:mr-3" %>
        <span class="text-xs sm:text-sm md:text-base">Morning Forest</span>
      </p>
    <% end %>

    <div class="flex items-center">
      <%= link_to "ログイン", login_path                                     , class: "mx-1 btn bg-gradient-to-tl from-emerald-300 to-emerald-100 btn-sm text-xs md:text-sm font-normal hover:opacity-60 sm:h-10 sm:w-20 sm:mx-2 md:mx-3 md:h-12 md:w-24 flex" %>
      <%= link_to "新規登録", new_user_path                                  , class: "mx-1 btn bg-gradient-to-tl from-cyan-400    to-cyan-100    btn-sm text-xs md:text-sm font-normal hover:opacity-60 sm:h-10 sm:w-20 sm:mx-2 md:mx-3 md:h-12 md:w-24 hidden sm:flex" %>
      <%= link_to "お試し"  , guest_login_path, data: { turbo_method: :post }, class: "mx-1 btn bg-gradient-to-tl from-pink-400    to-pink-100    btn-sm text-xs md:text-sm font-normal hover:opacity-60 sm:h-10 sm:w-20 sm:mx-2 md:mx-3 md:h-12 md:w-24 hidden sm:flex" %>
      
      <div class="drawer drawer-end mx-3 lg:mx-5 sm:hidden">
        <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content">
          <label for="my-drawer-4" class="drawer-button btn btn-sm bg-green-50 text-xl font-light sm:btn-md sm:text-3xl lg:size-14 lg:text-4xl">≡</label>
        </div>
        <div class="drawer-side mt-12 sm:mt-16 md:mt-20 lg:mt-24">
          <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
          <ul class="menu text-base-content w-4/12 bg-green-50 rounded-box z-10 shadow text-black w-40 sm:w-4/12 md:w-48 lg:w-52">
            <li><%= link_to "新規登録"  , new_user_path                                  , class: "m-1 btn bg-gradient-to-tl from-cyan-300    to-cyan-100    btn-sm text-xs font-normal hover:opacity-60 sm:btn-md sm:mx-2 md:mx-3" %></li>
            <li><%= link_to "ログイン"  , login_path                                     , class: "m-1 btn bg-gradient-to-tl from-emerald-300 to-emerald-100 btn-sm text-xs font-normal hover:opacity-60 sm:btn-md sm:mx-2 md:mx-3" %></li>
            <li><%= link_to "お試し利用", guest_login_path, data: { turbo_method: :post }, class: "m-1 btn bg-gradient-to-tl from-pink-300    to-pink-100    btn-sm text-xs font-normal hover:opacity-60 sm:btn-md sm:mx-2 md:mx-3" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="bg-red-400 w-10/12 p-2 mt-3 mb-5 rounded-lg mx-auto text-xs items-center sm:text-sm md:text-base lg:w-8/12">
    <p class="font-semibold mb-3">入力エラー</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div id="flash-container-<%= message_type %>" class="<%= flash_type_class(message_type) %> alert flex justify-between items-center text-white py-2 px-5 w-full text-sm md:text-base">
    <div class="flex gap-3 items-center">
      <i class="<%= flash_icon(message_type) %>"></i>
      <%= message %>
    </div>

    <button class="btn btn-ghost btn-xs btn-circle">
      <i class="i-uiw-close flash-close-btn"></i>
    </button>
  </div>
<% end %>

<!-- turbostreamで置き換え後も機能するように、scriptタグで記述 -->
<script>
  document.querySelectorAll('.flash-close-btn').forEach((btn) => {
    btn.addEventListener('click', (e) => {
      e.target.parentElement.parentElement.classList.add("hidden");
    });
  });
</script>

app/views/shared/_footer.html.erb
<footer>
  <div class="w-full h-12 sm:h-14 py-3 px-5 sm:px-8 md:px-10 hidden sm:flex justify-end items-center bg-gradient-to-b from-green-200 to-green-400">
    <div class="flex items-center gap-3 sm:gap-5">
      <%= link_to "お問い合わせ"        , new_contact_path, class: "mx-1 text-xs font-normal hover:text-blue-700 sm:mx-2 md:mx-3 md:text-sm" %>
      <%= link_to "プライバシーポリシー", policy_path     , class: "mx-1 text-xs font-normal hover:text-blue-700 sm:mx-2 md:mx-3 md:text-sm" %>
      <%= link_to "利用規約"            , terms_path      , class: "mx-1 text-xs font-normal hover:text-blue-700 sm:mx-2 md:mx-3 md:text-sm" %>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header id="logged-in-header" class="mb-9 sm:mb-[4.5rem] lg:mb-[5.5rem]">

  <div class="flex flex-col fixed top-0 z-50 w-full h-9 sm:h-[4.5rem] lg:h-[5.5rem]">
    
    <!-- ヘッダー -->
    <div class="flex justify-between items-center
                bg-gradient-to-t from-sky-100 to-sky-200
                w-full h-9 sm:h-10 lg:h-12"
    >

      <%= link_to root_page, class:"btn btn-sm border-none shadow-none w-28 sm:w-36 sm:h-10 md:w-44 md:h-12 bg-inherit bg-opacity-30 text-green-600 hover:bg-green-100", id: "logo-btn" do %>
        <p class="flex items-center gap-1">
          <%= image_tag "logo.jpg", class: "rounded h-6 sm:h-8" %>
          <span class="text-xs leading-[0.8rem] md:text-sm md:leading-[1rem]">Morning<br>Forest</span>
        </p>
      <% end %>

      <div class="flex items-center gap-3">
        <!-- ゲストログイン時のみ -->
        <% if current_user.guest? %>
          <%= link_to '本会員登録', new_user_path,
              class: "btn btn-accent btn-xs sm:btn-sm mx-3 lg:mx-5"
          %>
        <% end %>

        <!-- ユーザーアイコン -->
        <div class="tooltip tooltip-bottom flex-none" data-tip="プロフィール">
          <%= link_to user_path(current_user), class: "hover:scale-105 block", id: "user-icon-btn" do %>
            <%= image_tag "user_icon.jpg",
                class:"items-center rounded-lg shadow-md size-7 sm:size-8 lg:size-9"
            %>
          <% end %>
        </div>          

        <!-- ≡メニュー -->
        <div class="drawer drawer-end mx-3 lg:mx-5">
          <input id="my-drawer" type="checkbox" class="drawer-toggle" />

          <div class="drawer-content flex items-center">
            <label for="my-drawer" class="drawer-button btn btn-sm bg-white text-gray-600 text-lg leading-none font-light p-0 min-h-0 h-7 w-7 shadow-md sm:h-8 sm:w-8 lg:h-9 lg:w-9 lg:text-2xl">≡</label>
          </div>

          <!-- Drawerで表示される部分 -->
          <div class="drawer-side mt-9 sm:mt-10 md:mt-12">
            <label for="my-drawer" aria-label="close sidebar" class="drawer-overlay"></label>
            <ul class="menu text-base-content w-6/12 bg-green-50 rounded-box z-10 shadow text-black w-40 sm:w-4/12 md:w-48 lg:w-52" id="drawer-menu">
              <li>
                <%= link_to "マイページへ", my_pages_path,
                    class: "p-3 mb-2 bg-gradient-to-tl from-green-300 to-green-100 text-xs sm:text-sm lg:text-base hover:opacity-50"
                %>
              </li>
              <li>
                <%= link_to "ルーティンを作成する", new_routine_path,
                    class:"p-3 mb-2 bg-gradient-to-tl from-cyan-300 to-cyan-100 text-xs sm:text-sm lg:text-base hover:opacity-50"
                %>
              </li>
              <li>
                <%= link_to "My ルーティン", routines_path,
                    class:"p-3 mb-2 bg-gradient-to-tl from-cyan-300 to-cyan-100 text-xs sm:text-sm lg:text-base hover:opacity-50"
                %>
              </li>
              <li>
                <%= link_to "投稿を見る", routines_posts_path,
                    class:"p-3 mb-2 bg-gradient-to-tl from-cyan-300 to-cyan-100 text-xs sm:text-sm lg:text-base hover:opacity-50"
                %>
              </li>
              <li>
                <%= link_to "称号一覧", rewards_path,
                    class:"p-3 mb-2 bg-gradient-to-tl from-cyan-300 to-cyan-100 text-xs sm:text-sm lg:text-base hover:opacity-50"
                %>
              </li>
              <li>
                <%= link_to "利用規約", terms_path,
                    class:"p-3 mb-2 bg-gradient-to-tl from-yellow-200 to-yellow-50 text-xs sm:text-sm hover:opacity-50"      
                %>
              </li>
              <li>
                <%= link_to "プライバシーポリシー", policy_path,
                    class:"p-3 mb-2 bg-gradient-to-tl from-yellow-200 to-yellow-50 text-xs sm:text-sm hover:opacity-50"
                %>
              </li>
              <li>
              <%= link_to "お問い合わせ", new_contact_path,
                  class:"p-3 mb-2 bg-gradient-to-tl from-yellow-200 to-yellow-50 text-xs sm:text-sm hover:opacity-50"
              %>
              </li>
              <li>
                <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete },
                    class:"p-3 mb-2 bg-gradient-to-tl from-gray-300 to-gray-100 text-xs sm:text-sm hover:opacity-50"
                %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- メニューバー -->
    <div class="hidden w-full bg-gradient-to-b from-sky-100 to-sky-50 sm:flex sm:h-9 lg:h-10">
      <%= render 'shared/nav_menu' %>
    </div>
  </div>
</header>

app/views/shared/_nav_bottom.html.erb
<div class="btm-nav btm-nav-sm z-50 sm:hidden">
  <%= link_to my_pages_path do %>
    <span class="i-uiw-home size-5"></span>
    <span class="text-[0.5rem]">マイページ</span>
  <% end %>

  <%= link_to routines_path do %>
    <span class="i-uiw-dashboard size-5"></span>
    <span class="text-[0.5rem]">My Routines</span>
  <% end %>

  <%= link_to new_routine_path do %>
    <span class="i-uiw-plus size-5"></span>
    <span class="text-[0.5rem]">新規作成</span>
  <% end %>

  <%= link_to routines_posts_path do %>
    <span class="i-uiw-search size-5"></span>
    <span class="text-[0.5rem]">投稿一覧</span>
  <% end %>

  <%= link_to user_path(current_user) do %>
    <span class="i-uiw-user size-5"></span>
    <span class="text-[0.5rem]">プロフィール</span>
  <% end %>
</div>

app/views/shared/_nav_menu.html.erb
<div class="w-10/12 mx-auto" id="header-menu">
  <div class="flex items-center justify-between lg:justify-start h-full">
    <%= link_to my_pages_path, class: "nav-menu-custom" do %>
      マイページ
    <% end %>

    <%= link_to routines_path, class: "nav-menu-custom" do %>
      My ルーティン
    <% end %>

    <%= link_to new_routine_path, class: "nav-menu-custom" do %>
      新規作成
    <% end %>
    
    <%= link_to routines_posts_path, class: "nav-menu-custom" do %>
      投稿を見る
    <% end %>
    
    <%= link_to rewards_path, class: "nav-menu-custom" do %>
      称号一覧
    <% end %>
    
    <%= link_to user_path(current_user), class: "nav-menu-custom" do %>
      プロフィール
    <% end %>
  </div>
</div>

app/views/shared/_quick_routine_create_btn.html.erb
<div class="flex items-center">
  <%= link_to '1 clickで作成',
      routines_quick_creates_path,
      data: {turbo_method: :post, tip: "ルーティンを作成できます"},
      class: "btn-md-custom btn-create-custom tooltip tooltip-accent",
      id: "quick-create-routine-btn"
  %>

  <button class="btn btn-md-custom btn-ghost" onclick="quick_routine_template_form_modal.showModal()">
    <i class="i-uiw-edit"></i>
  </button>
</div>

<!-- Modal 編集フォーム -->
<dialog id="quick_routine_template_form_modal" class="modal">
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>

  <div class="modal-box">
    <%= render 'quick_routine_templates/edit_form',
        quick_routine_template: quick_routine_template %>

    <div class="modal-action">
      <form method="dialog">
        <button class="btn btn-md-custom btn-cancel-custom">キャンセル</button>
      </form>
    </div>
  </div>
</dialog>